server:
  port: 9001
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YamilRios/bc26-project2.git
          search-paths: config-data
          default-label: ${GIT_BRANCH}
          username: ${GIT_USER}
          password: ${GIT_PSWD}